// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIkpEwEBKcFL4LEloQhKmrtnJ1gmUeIL0',
    appId: '1:54839629013:web:0d03f8d8395c1058d53e5c',
    messagingSenderId: '54839629013',
    projectId: 'flutter-suivi',
    authDomain: 'flutter-suivi.firebaseapp.com',
    storageBucket: 'flutter-suivi.firebasestorage.app',
    measurementId: 'G-ZX56RK47JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKy8luYTbN39Ezo5lp88gJaQQi6LOofPg',
    appId: '1:54839629013:android:eb84e86f9a3ce98cd53e5c',
    messagingSenderId: '54839629013',
    projectId: 'flutter-suivi',
    storageBucket: 'flutter-suivi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENFULWZht3G-SuYvIIVOhtXfIzXKInCA',
    appId: '1:54839629013:ios:d1840180bb2e134bd53e5c',
    messagingSenderId: '54839629013',
    projectId: 'flutter-suivi',
    storageBucket: 'flutter-suivi.firebasestorage.app',
    iosBundleId: 'com.example.tp1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBENFULWZht3G-SuYvIIVOhtXfIzXKInCA',
    appId: '1:54839629013:ios:d1840180bb2e134bd53e5c',
    messagingSenderId: '54839629013',
    projectId: 'flutter-suivi',
    storageBucket: 'flutter-suivi.firebasestorage.app',
    iosBundleId: 'com.example.tp1Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIkpEwEBKcFL4LEloQhKmrtnJ1gmUeIL0',
    appId: '1:54839629013:web:03807270c571ab7dd53e5c',
    messagingSenderId: '54839629013',
    projectId: 'flutter-suivi',
    authDomain: 'flutter-suivi.firebaseapp.com',
    storageBucket: 'flutter-suivi.firebasestorage.app',
    measurementId: 'G-KJDMYMM1JE',
  );
}
